<?php

use Entities\Movie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoviesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('movies')->delete();

        $movies = array(
            array('id' => '1','title' => 'The Shawshank Redemption','year' => '1994','rated' => 'R','released' => '14 Oct 1994','runtime' => '142 min','director' => 'Frank Darabont','writer' => 'Stephen King (short story "Rita Hayworth and Shawshank Redemption"), Frank Darabont (screenplay)','actors' => 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler','plot' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.','country' => 'USA','awards' => 'Nominated for 7 Oscars. Another 19 wins & 30 nominations.','poster' => 'tt0111161_poster.jpg','metascore' => '80','imdb_rating' => '9.3','imdb_votes' => '1,738,596','imdb_id' => 'tt0111161','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:44','updated_at' => '2016-12-13 23:38:03'),
            array('id' => '2','title' => 'The Godfather','year' => '1972','rated' => 'R','released' => '24 Mar 1972','runtime' => '175 min','director' => 'Francis Ford Coppola','writer' => 'Mario Puzo (screenplay), Francis Ford Coppola (screenplay), Mario Puzo (novel)','actors' => 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano','plot' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','country' => 'USA','awards' => 'Won 3 Oscars. Another 23 wins & 27 nominations.','poster' => 'tt0068646_poster.jpg','metascore' => '100','imdb_rating' => '9.2','imdb_votes' => '1,186,027','imdb_id' => 'tt0068646','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:44','updated_at' => '2016-12-13 23:38:04'),
            array('id' => '3','title' => 'The Godfather: Part II','year' => '1974','rated' => 'R','released' => '20 Dec 1974','runtime' => '202 min','director' => 'Francis Ford Coppola','writer' => 'Francis Ford Coppola (screenplay), Mario Puzo (screenplay), Mario Puzo (novel)','actors' => 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro','plot' => 'The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.','country' => 'USA','awards' => 'Won 6 Oscars. Another 10 wins & 20 nominations.','poster' => 'tt0071562_poster.jpg','metascore' => '80','imdb_rating' => '9.0','imdb_votes' => '813,863','imdb_id' => 'tt0071562','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:45','updated_at' => '2016-12-13 23:38:05'),
            array('id' => '4','title' => 'The Dark Knight','year' => '2008','rated' => 'PG-13','released' => '18 Jul 2008','runtime' => '152 min','director' => 'Christopher Nolan','writer' => 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)','actors' => 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine','plot' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.','country' => 'USA, UK','awards' => 'Won 2 Oscars. Another 146 wins & 142 nominations.','poster' => 'tt0468569_poster.jpg','metascore' => '82','imdb_rating' => '9.0','imdb_votes' => '1,713,318','imdb_id' => 'tt0468569','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:45','updated_at' => '2016-12-13 23:38:06'),
            array('id' => '5','title' => '12 Angry Men','year' => '1957','rated' => 'APPROVED','released' => '01 Apr 1957','runtime' => '96 min','director' => 'Sidney Lumet','writer' => 'Reginald Rose (story), Reginald Rose (screenplay)','actors' => 'Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall','plot' => 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.','country' => 'USA','awards' => 'Nominated for 3 Oscars. Another 16 wins & 8 nominations.','poster' => 'tt0050083_poster.jpg','metascore' => 'N/A','imdb_rating' => '8.9','imdb_votes' => '462,820','imdb_id' => 'tt0050083','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:45','updated_at' => '2016-12-13 23:38:07'),
            array('id' => '6','title' => 'Schindler\'s List','year' => '1993','rated' => 'R','released' => '04 Feb 1994','runtime' => '195 min','director' => 'Steven Spielberg','writer' => 'Thomas Keneally (book), Steven Zaillian (screenplay)','actors' => 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall','plot' => 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans.','country' => 'USA','awards' => 'Won 7 Oscars. Another 71 wins & 33 nominations.','poster' => 'tt0108052_poster.jpg','metascore' => '93','imdb_rating' => '8.9','imdb_votes' => '890,631','imdb_id' => 'tt0108052','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:45','updated_at' => '2016-12-13 23:38:08'),
            array('id' => '7','title' => 'Pulp Fiction','year' => '1994','rated' => 'R','released' => '14 Oct 1994','runtime' => '154 min','director' => 'Quentin Tarantino','writer' => 'Quentin Tarantino (story), Roger Avary (story), Quentin Tarantino','actors' => 'Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta','plot' => 'The lives of two mob hit men, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','country' => 'USA','awards' => 'Won 1 Oscar. Another 60 wins & 65 nominations.','poster' => 'tt0110912_poster.jpg','metascore' => '94','imdb_rating' => '8.9','imdb_votes' => '1,353,269','imdb_id' => 'tt0110912','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:46','updated_at' => '2016-12-13 23:38:09'),
            array('id' => '8','title' => 'The Lord of the Rings: The Return of the King','year' => '2003','rated' => 'PG-13','released' => '17 Dec 2003','runtime' => '201 min','director' => 'Peter Jackson','writer' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)','actors' => 'Noel Appleby, Ali Astin, Sean Astin, David Aston','plot' => 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.','country' => 'USA, New Zealand','awards' => 'Won 11 Oscars. Another 174 wins & 113 nominations.','poster' => 'tt0167260_poster.jpg','metascore' => '94','imdb_rating' => '8.9','imdb_votes' => '1,247,523','imdb_id' => 'tt0167260','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:46','updated_at' => '2016-12-13 23:38:10'),
            array('id' => '9','title' => 'The Good, the Bad and the Ugly','year' => '1966','rated' => 'APPROVED','released' => '29 Dec 1967','runtime' => '161 min','director' => 'Sergio Leone','writer' => 'Luciano Vincenzoni (story), Sergio Leone (story), Agenore Incrocci (screenplay), Furio Scarpelli (screenplay), Luciano Vincenzoni (screenplay), Sergio Leone (screenplay), Mickey Knox (English version by)','actors' => 'Eli Wallach, Clint Eastwood, Lee Van Cleef, Aldo Giuffrè','plot' => 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.','country' => 'Italy, Spain, West Germany, USA','awards' => '1 win & 1 nomination.','poster' => 'tt0060196_poster.jpg','metascore' => '90','imdb_rating' => '8.9','imdb_votes' => '514,659','imdb_id' => 'tt0060196','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:46','updated_at' => '2016-12-13 23:38:11'),
            array('id' => '10','title' => 'Fight Club','year' => '1999','rated' => 'R','released' => '15 Oct 1999','runtime' => '139 min','director' => 'David Fincher','writer' => 'Chuck Palahniuk (novel), Jim Uhls (screenplay)','actors' => 'Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier','plot' => 'An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more.','country' => 'USA, Germany','awards' => 'Nominated for 1 Oscar. Another 10 wins & 31 nominations.','poster' => 'tt0137523_poster.jpg','metascore' => '66','imdb_rating' => '8.8','imdb_votes' => '1,384,393','imdb_id' => 'tt0137523','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:47','updated_at' => '2016-12-13 23:38:12'),
            array('id' => '11','title' => 'The Lord of the Rings: The Fellowship of the Ring','year' => '2001','rated' => 'PG-13','released' => '19 Dec 2001','runtime' => '178 min','director' => 'Peter Jackson','writer' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)','actors' => 'Alan Howard, Noel Appleby, Sean Astin, Sala Baker','plot' => 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle Earth from the Dark Lord Sauron.','country' => 'New Zealand, USA','awards' => 'Won 4 Oscars. Another 108 wins & 122 nominations.','poster' => 'tt0120737_poster.jpg','metascore' => '92','imdb_rating' => '8.8','imdb_votes' => '1,269,564','imdb_id' => 'tt0120737','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:47','updated_at' => '2016-12-13 23:38:13'),
            array('id' => '12','title' => 'Star Wars: Episode V - The Empire Strikes Back','year' => '1980','rated' => 'PG','released' => '20 Jun 1980','runtime' => '124 min','director' => 'Irvin Kershner','writer' => 'Leigh Brackett (screenplay), Lawrence Kasdan (screenplay), George Lucas (story by)','actors' => 'Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams','plot' => 'After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.','country' => 'USA','awards' => 'Won 1 Oscar. Another 19 wins & 18 nominations.','poster' => 'tt0080684_poster.jpg','metascore' => '80','imdb_rating' => '8.8','imdb_votes' => '861,526','imdb_id' => 'tt0080684','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:47','updated_at' => '2016-12-13 23:38:14'),
            array('id' => '13','title' => 'Forrest Gump','year' => '1994','rated' => 'PG-13','released' => '06 Jul 1994','runtime' => '142 min','director' => 'Robert Zemeckis','writer' => 'Winston Groom (novel), Eric Roth (screenplay)','actors' => 'Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys','plot' => 'Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.','country' => 'USA','awards' => 'Won 6 Oscars. Another 39 wins & 65 nominations.','poster' => 'tt0109830_poster.jpg','metascore' => '82','imdb_rating' => '8.8','imdb_votes' => '1,291,467','imdb_id' => 'tt0109830','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:47','updated_at' => '2016-12-13 23:38:15'),
            array('id' => '14','title' => 'Inception','year' => '2010','rated' => 'PG-13','released' => '16 Jul 2010','runtime' => '148 min','director' => 'Christopher Nolan','writer' => 'Christopher Nolan','actors' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy','plot' => 'A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.','country' => 'USA, UK','awards' => 'Won 4 Oscars. Another 144 wins & 198 nominations.','poster' => 'tt1375666_poster.jpg','metascore' => '74','imdb_rating' => '8.8','imdb_votes' => '1,512,813','imdb_id' => 'tt1375666','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:48','updated_at' => '2016-12-13 23:38:16'),
            array('id' => '15','title' => 'The Lord of the Rings: The Two Towers','year' => '2002','rated' => 'PG-13','released' => '18 Dec 2002','runtime' => '179 min','director' => 'Peter Jackson','writer' => 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Stephen Sinclair (screenplay), Peter Jackson (screenplay)','actors' => 'Bruce Allpress, Sean Astin, John Bach, Sala Baker','plot' => 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.','country' => 'USA, New Zealand','awards' => 'Won 2 Oscars. Another 114 wins & 127 nominations.','poster' => 'tt0167261_poster.jpg','metascore' => '88','imdb_rating' => '8.7','imdb_votes' => '1,128,540','imdb_id' => 'tt0167261','type' => 'movie','system_data' => '1','created_at' => '2016-12-13 23:04:48','updated_at' => '2016-12-13 23:38:17'),
        );

        foreach($movies as $movie){
            Movie::create($movie);
        }

    }
}
